import type {
  Consultation,
  Doctor,
  Facility,
  HealthRecord,
  Patient,
  Referral,
  Assessment,
} from "./types";

export const FACILITIES: Facility[] = [
  {
    id: "F1",
    name: "Jangipur Primary Health Centre",
    type: "PHC",
    distanceKm: 2.4,
    doctors: 2,
    services: ["OPD", "Immunisation", "Basic Lab", "Maternal Care"],
    waitMinutes: 15,
    emergency: false,
    x: 26,
    y: 62,
  },
  {
    id: "F2",
    name: "Raghunathganj Rural Community Health Centre",
    type: "CHC",
    distanceKm: 7.8,
    doctors: 6,
    services: ["OPD", "Minor Surgery", "X-Ray", "Delivery", "Pharmacy"],
    waitMinutes: 30,
    emergency: true,
    x: 48,
    y: 38,
  },
  {
    id: "F3",
    name: "Murshidabad District Hospital",
    type: "District Hospital",
    distanceKm: 18.5,
    doctors: 24,
    services: ["Emergency", "ICU", "Surgery", "Radiology", "Blood Bank"],
    waitMinutes: 45,
    emergency: true,
    x: 70,
    y: 60,
  },
  {
    id: "F4",
    name: "Berhampore Cardiac & Trauma Centre",
    type: "Specialist Hospital",
    distanceKm: 26.2,
    doctors: 18,
    services: ["Cardiology", "Trauma", "Cath Lab", "24x7 Emergency"],
    waitMinutes: 20,
    emergency: true,
    x: 84,
    y: 26,
  },
  {
    id: "F5",
    name: "Sagardighi Sub-Divisional PHC",
    type: "PHC",
    distanceKm: 5.1,
    doctors: 1,
    services: ["OPD", "TB DOTS", "Antenatal Care"],
    waitMinutes: 10,
    emergency: false,
    x: 18,
    y: 26,
  },
];

export const DOCTORS: Doctor[] = [
  {
    id: "D1",
    name: "Dr. Ananya Sharma",
    specialization: "General Medicine",
    facility: "Murshidabad District Hospital",
    languages: ["English", "Hindi", "Bengali"],
    experience: 11,
    slots: ["09:30 AM", "11:00 AM", "02:30 PM", "05:00 PM"],
    rating: 4.8,
  },
  {
    id: "D2",
    name: "Dr. Rahul Das",
    specialization: "Cardiology",
    facility: "Berhampore Cardiac & Trauma Centre",
    languages: ["English", "Bengali"],
    experience: 15,
    slots: ["10:00 AM", "01:00 PM", "04:00 PM"],
    rating: 4.9,
  },
  {
    id: "D3",
    name: "Dr. Priya Singh",
    specialization: "Pediatrics",
    facility: "Raghunathganj Rural CHC",
    languages: ["Hindi", "English"],
    experience: 8,
    slots: ["09:00 AM", "12:00 PM", "03:30 PM"],
    rating: 4.7,
  },
  {
    id: "D4",
    name: "Dr. Imran Hossain",
    specialization: "Pulmonology",
    facility: "Murshidabad District Hospital",
    languages: ["Bengali", "English"],
    experience: 12,
    slots: ["11:30 AM", "02:00 PM"],
    rating: 4.6,
  },
  {
    id: "D5",
    name: "Dr. Meera Ghosh",
    specialization: "Obstetrics & Gynaecology",
    facility: "Raghunathganj Rural CHC",
    languages: ["Bengali", "Hindi"],
    experience: 9,
    slots: ["10:30 AM", "01:30 PM", "04:30 PM"],
    rating: 4.8,
  },
];

export const PATIENTS: Patient[] = [
  {
    id: "P1",
    healthId: "SW-2026-100241",
    name: "Rekha Mondal",
    age: 34,
    gender: "Female",
    mobile: "98300 11221",
    village: "Jangipur",
    district: "Murshidabad",
    state: "West Bengal",
    bloodGroup: "B+",
    emergencyContact: "98300 11222",
    assignedWorker: "Sunita Bibi",
    risk: "MODERATE",
    createdAt: "2026-07-14",
  },
  {
    id: "P2",
    healthId: "SW-2026-100242",
    name: "Abdul Rahman",
    age: 62,
    gender: "Male",
    mobile: "98311 45090",
    village: "Sagardighi",
    district: "Murshidabad",
    state: "West Bengal",
    bloodGroup: "O+",
    emergencyContact: "98311 45091",
    assignedWorker: "Sunita Bibi",
    risk: "HIGH",
    createdAt: "2026-07-19",
  },
  {
    id: "P3",
    healthId: "SW-2026-100243",
    name: "Kiran Yadav",
    age: 4,
    gender: "Male",
    mobile: "90070 33112",
    village: "Raghunathganj",
    district: "Murshidabad",
    state: "West Bengal",
    bloodGroup: "A+",
    emergencyContact: "90070 33113",
    assignedWorker: "Sunita Bibi",
    risk: "MODERATE",
    createdAt: "2026-08-02",
  },
  {
    id: "P4",
    healthId: "SW-2026-100244",
    name: "Fatima Khatun",
    age: 27,
    gender: "Female",
    mobile: "89020 77341",
    village: "Nabagram",
    district: "Murshidabad",
    state: "West Bengal",
    bloodGroup: "AB+",
    emergencyContact: "89020 77342",
    assignedWorker: "Sunita Bibi",
    risk: "LOW",
    createdAt: "2026-08-08",
  },
  {
    id: "P5",
    healthId: "SW-2026-100245",
    name: "Gopal Sarkar",
    age: 71,
    gender: "Male",
    mobile: "70030 55214",
    village: "Beldanga",
    district: "Murshidabad",
    state: "West Bengal",
    bloodGroup: "B-",
    emergencyContact: "70030 55215",
    assignedWorker: "Sunita Bibi",
    risk: "EMERGENCY",
    createdAt: "2026-08-11",
  },
  {
    id: "P6",
    healthId: "SW-2026-100246",
    name: "Salma Begum",
    age: 45,
    gender: "Female",
    mobile: "87770 21930",
    village: "Domkal",
    district: "Murshidabad",
    state: "West Bengal",
    bloodGroup: "O-",
    emergencyContact: "87770 21931",
    assignedWorker: "Rina Das",
    risk: "MODERATE",
    createdAt: "2026-08-15",
  },
  {
    id: "P7",
    healthId: "SW-2026-100247",
    name: "Bijoy Ghosh",
    age: 19,
    gender: "Male",
    mobile: "91630 40876",
    village: "Kandi",
    district: "Murshidabad",
    state: "West Bengal",
    bloodGroup: "A-",
    emergencyContact: "91630 40877",
    assignedWorker: "Rina Das",
    risk: "LOW",
    createdAt: "2026-08-18",
  },
  {
    id: "P8",
    healthId: "SW-2026-100248",
    name: "Anita Hembram",
    age: 52,
    gender: "Female",
    mobile: "76050 66123",
    village: "Bharatpur",
    district: "Murshidabad",
    state: "West Bengal",
    bloodGroup: "B+",
    emergencyContact: "76050 66124",
    assignedWorker: "Rina Das",
    risk: "HIGH",
    createdAt: "2026-08-21",
  },
  {
    id: "P9",
    healthId: "SW-2026-100249",
    name: "Sujata Pal",
    age: 30,
    gender: "Female",
    mobile: "88200 99001",
    village: "Lalgola",
    district: "Murshidabad",
    state: "West Bengal",
    bloodGroup: "O+",
    emergencyContact: "88200 99002",
    assignedWorker: "Sunita Bibi",
    risk: "LOW",
    createdAt: "2026-08-25",
  },
  {
    id: "P10",
    healthId: "SW-2026-100250",
    name: "Hafiz Sheikh",
    age: 58,
    gender: "Male",
    mobile: "97480 31007",
    village: "Farakka",
    district: "Murshidabad",
    state: "West Bengal",
    bloodGroup: "A+",
    emergencyContact: "97480 31008",
    assignedWorker: "Sunita Bibi",
    risk: "MODERATE",
    createdAt: "2026-08-29",
  },
];

export const REFERRALS: Referral[] = [
  {
    id: "REF-SW-2026-10001",
    patientId: "P2",
    patientName: "Abdul Rahman",
    fromFacility: "Sagardighi Sub-Divisional PHC",
    toFacility: "Murshidabad District Hospital",
    reason: "Uncontrolled hypertension with chest discomfort",
    priority: "Urgent",
    notes: "BP 178/104. Needs ECG and cardiology review.",
    status: "Treatment Started",
    createdAt: "2026-08-28",
  },
  {
    id: "REF-SW-2026-10002",
    patientId: "P5",
    patientName: "Gopal Sarkar",
    fromFacility: "Jangipur Primary Health Centre",
    toFacility: "Berhampore Cardiac & Trauma Centre",
    reason: "Acute chest pain, suspected cardiac event",
    priority: "Emergency",
    notes: "Ambulance dispatched via 108.",
    status: "Arrived",
    createdAt: "2026-09-01",
  },
  {
    id: "REF-SW-2026-10003",
    patientId: "P8",
    patientName: "Anita Hembram",
    fromFacility: "Raghunathganj Rural Community Health Centre",
    toFacility: "Murshidabad District Hospital",
    reason: "Persistent fever 8 days, suspected typhoid",
    priority: "Urgent",
    notes: "Widal test pending.",
    status: "Patient Traveling",
    createdAt: "2026-09-02",
  },
  {
    id: "REF-SW-2026-10004",
    patientId: "P3",
    patientName: "Kiran Yadav",
    fromFacility: "Jangipur Primary Health Centre",
    toFacility: "Raghunathganj Rural Community Health Centre",
    reason: "Paediatric dehydration follow-up",
    priority: "Routine",
    notes: "ORS started at PHC.",
    status: "Completed",
    createdAt: "2026-08-20",
  },
  {
    id: "REF-SW-2026-10005",
    patientId: "P1",
    patientName: "Rekha Mondal",
    fromFacility: "Jangipur Primary Health Centre",
    toFacility: "Raghunathganj Rural Community Health Centre",
    reason: "Anaemia in pregnancy",
    priority: "Routine",
    notes: "Hb 8.2 g/dL.",
    status: "Accepted",
    createdAt: "2026-09-03",
  },
  {
    id: "REF-SW-2026-10006",
    patientId: "P6",
    patientName: "Salma Begum",
    fromFacility: "Sagardighi Sub-Divisional PHC",
    toFacility: "Murshidabad District Hospital",
    reason: "Diabetic foot ulcer",
    priority: "Urgent",
    notes: "Dressing done. Needs surgical review.",
    status: "Created",
    createdAt: "2026-09-03",
  },
  {
    id: "REF-SW-2026-10007",
    patientId: "P10",
    patientName: "Hafiz Sheikh",
    fromFacility: "Jangipur Primary Health Centre",
    toFacility: "Raghunathganj Rural Community Health Centre",
    reason: "Chronic cough > 3 weeks, TB screening",
    priority: "Urgent",
    notes: "Sputum sample collected.",
    status: "Accepted",
    createdAt: "2026-09-02",
  },
  {
    id: "REF-SW-2026-10008",
    patientId: "P4",
    patientName: "Fatima Khatun",
    fromFacility: "Jangipur Primary Health Centre",
    toFacility: "Raghunathganj Rural Community Health Centre",
    reason: "Routine antenatal ultrasound",
    priority: "Routine",
    notes: "28 weeks gestation.",
    status: "Completed",
    createdAt: "2026-08-12",
  },
  {
    id: "REF-SW-2026-10009",
    patientId: "P9",
    patientName: "Sujata Pal",
    fromFacility: "Sagardighi Sub-Divisional PHC",
    toFacility: "Murshidabad District Hospital",
    reason: "Recurrent migraine, neurology opinion",
    priority: "Routine",
    notes: "No red-flag signs.",
    status: "Created",
    createdAt: "2026-09-04",
  },
  {
    id: "REF-SW-2026-10010",
    patientId: "P7",
    patientName: "Bijoy Ghosh",
    fromFacility: "Jangipur Primary Health Centre",
    toFacility: "Murshidabad District Hospital",
    reason: "Fracture follow-up X-ray",
    priority: "Routine",
    notes: "Cast applied 3 weeks ago.",
    status: "Completed",
    createdAt: "2026-08-05",
  },
];

export const CONSULTATIONS: Consultation[] = [
  {
    id: "C1",
    patientId: "P1",
    patientName: "Rekha Mondal",
    doctorName: "Dr. Meera Ghosh",
    date: "2026-09-04",
    slot: "10:30 AM",
    mode: "Video",
    status: "Scheduled",
  },
  {
    id: "C2",
    patientId: "P2",
    patientName: "Abdul Rahman",
    doctorName: "Dr. Rahul Das",
    date: "2026-09-04",
    slot: "01:00 PM",
    mode: "Video",
    status: "Scheduled",
  },
  {
    id: "C3",
    patientId: "P3",
    patientName: "Kiran Yadav",
    doctorName: "Dr. Priya Singh",
    date: "2026-09-01",
    slot: "12:00 PM",
    mode: "Video",
    status: "Completed",
    notes: "Mild gastroenteritis. Hydration advised.",
    prescription: "ORS sachets x10, Zinc syrup 5ml OD x14 days",
    followUp: "2026-09-08",
  },
  {
    id: "C4",
    patientId: "P8",
    patientName: "Anita Hembram",
    doctorName: "Dr. Ananya Sharma",
    date: "2026-09-03",
    slot: "11:00 AM",
    mode: "Video",
    status: "Completed",
    notes: "Persistent fever. Blood tests ordered.",
    prescription: "Paracetamol 650mg TDS x5 days",
    followUp: "2026-09-07",
  },
  {
    id: "C5",
    patientId: "P10",
    patientName: "Hafiz Sheikh",
    doctorName: "Dr. Imran Hossain",
    date: "2026-09-04",
    slot: "02:00 PM",
    mode: "Video",
    status: "Scheduled",
  },
];

export const ASSESSMENTS: Assessment[] = [
  {
    id: "A1",
    patientId: "P2",
    symptoms: ["Chest pain", "Weakness"],
    duration: "1-3",
    severity: 8,
    conditions: ["Hypertension"],
    risk: "EMERGENCY",
    score: 78,
    action: "Go to the nearest emergency hospital now or call 108 for an ambulance.",
    facilityType: "Emergency Hospital",
    reasons: ["Chest pain is a red-flag symptom"],
    createdAt: "2026-08-28",
  },
  {
    id: "A2",
    patientId: "P1",
    symptoms: ["Weakness", "Dizziness"],
    duration: "4-7",
    severity: 5,
    conditions: ["Pregnancy"],
    risk: "MODERATE",
    score: 39,
    action: "Book a teleconsultation today or visit your PHC/CHC.",
    facilityType: "PHC or CHC",
    reasons: ["Dizziness with weakness may indicate anaemia"],
    createdAt: "2026-09-03",
  },
];

export const RECORDS: HealthRecord[] = [
  {
    id: "R1",
    patientId: "P1",
    type: "Assessment",
    title: "AI triage — Moderate risk",
    detail: "Weakness and dizziness for 4-7 days during pregnancy. Advised CHC review.",
    date: "2026-09-03",
  },
  {
    id: "R2",
    patientId: "P1",
    type: "Referral",
    title: "REF-SW-2026-10005 created",
    detail: "Referred to Raghunathganj Rural CHC for anaemia in pregnancy.",
    date: "2026-09-03",
  },
  {
    id: "R3",
    patientId: "P1",
    type: "Report",
    title: "Haemoglobin test",
    detail: "Hb 8.2 g/dL — moderate anaemia.",
    date: "2026-09-02",
  },
  {
    id: "R4",
    patientId: "P2",
    type: "Consultation",
    title: "Cardiology teleconsultation",
    detail: "Dr. Rahul Das reviewed ECG. Advised admission.",
    date: "2026-08-29",
  },
  {
    id: "R5",
    patientId: "P2",
    type: "Prescription",
    title: "Amlodipine 5mg OD, Aspirin 75mg OD",
    detail: "Continue for 30 days, monitor BP daily.",
    date: "2026-08-29",
  },
  {
    id: "R6",
    patientId: "P3",
    type: "Follow-up",
    title: "Paediatric follow-up scheduled",
    detail: "Review hydration and weight on 08 Sep 2026.",
    date: "2026-09-01",
  },
];

export const HEALTH_WORKERS = [
  { id: "W1", name: "Sunita Bibi", village: "Jangipur", patients: 7 },
  { id: "W2", name: "Rina Das", village: "Kandi", patients: 3 },
  { id: "W3", name: "Mamata Sil", village: "Domkal", patients: 5 },
  { id: "W4", name: "Jharna Roy", village: "Farakka", patients: 4 },
  { id: "W5", name: "Anwara Bibi", village: "Lalgola", patients: 6 },
];

export const MONTHLY_CONSULTATIONS = [
  { month: "Mar", consultations: 128 },
  { month: "Apr", consultations: 164 },
  { month: "May", consultations: 191 },
  { month: "Jun", consultations: 210 },
  { month: "Jul", consultations: 248 },
  { month: "Aug", consultations: 302 },
];

export const COMMON_SYMPTOMS = [
  { symptom: "Fever", count: 184 },
  { symptom: "Cough", count: 141 },
  { symptom: "Weakness", count: 118 },
  { symptom: "Stomach pain", count: 96 },
  { symptom: "Headache", count: 84 },
  { symptom: "Breathing difficulty", count: 47 },
];

export const FACILITY_USAGE = [
  { facility: "Jangipur PHC", visits: 320 },
  { facility: "Sagardighi PHC", visits: 214 },
  { facility: "Raghunathganj CHC", visits: 268 },
  { facility: "Murshidabad DH", visits: 189 },
  { facility: "Berhampore Specialist", visits: 76 },
];
